version: '{build}'
image: "Visual Studio 2019"
clone_depth: 5
environment:
  matrix:
  - PYTHON: "C:\\Python35-x64"
    PYTHON_VERSION: "3.5"
    PYTHON_ARCH: "64"
  - PYTHON: "C:\\Python36-x64"
    PYTHON_VERSION: "3.6"
    PYTHON_ARCH: "64"
  - PYTHON: "C:\\Python37-x64"
    PYTHON_VERSION: "3.7"
    PYTHON_ARCH: "64"
  - PYTHON: "C:\\Python38-x64"
    PYTHON_VERSION: "3.8"
    PYTHON_ARCH: "64"
  - PYTHON: "C:\\Python39-x64"
    PYTHON_VERSION: "3.9"
    PYTHON_ARCH: "64"

cache:
  - build -> appveyor.yml

install:
- "git submodule update --init"
- "%PYTHON%\\python.exe -m pip install -r ci\\requirements.txt"
- "%PYTHON%\\python.exe -m pip install twine"

before_build:
- "%PYTHON%\\python.exe -V"

build_script:
- "%PYTHON%\\python.exe setup.py build_clib --debug"
- "%PYTHON%\\python.exe setup.py build_ext  --inplace"

test_script:
- "%PYTHON%\\python.exe -m coverage run -m unittest discover -b -v"

after_test:
- "%PYTHON%\\python.exe -m coverage xml"
- "%PYTHON%\\python.exe -m coverage report"
- "%PYTHON%\\python.exe -m codecov"

before_deploy:
- "%PYTHON%\\python.exe setup.py clean --all"
- "%PYTHON%\\python.exe setup.py sdist bdist_wheel"
- "%PYTHON%\\python.exe -m twine check dist\\*"

deploy_script:
- ps: .\ci\appveyor\deploy.ps1
