stages:
  - test
  - bdist

variables:
  GIT_DEPTH: 100
  GIT_SUBMODULE_STRATEGY: recursive
  TWINE_USERNAME: gitlab-ci-token
  TWINE_PASSWORD: $CI_JOB_TOKEN

# --- Stage Templates ----------------------------------------------------------

.test: &test
  image: quay.io/pypa/manylinux2010_x86_64
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - build
  only:
  - master
  before_script:
    - $python -m pip install -U -r ci/requirements.txt
  script:
    - $python setup.py build_clib --debug
    - $python setup.py build_ext  --debug --inplace
    - $python -m coverage run -m unittest discover -v
  after_script:
    - $python -m coverage xml
    - $python -m coverage report
    - $python -m codecov
  artifacts:
    reports:
      cobertura: coverage.xml


# --- Stages -------------------------------------------------------------------

test:python3.6:
  environment:
    name: Python 3.6
  variables:
    python: /opt/python/cp36-cp36m/bin/python
  <<: *test

test:python3.7:
  environment:
    name: Python 3.7
  variables:
    python: /opt/python/cp37-cp37m/bin/python
  <<: *test

test:python3.8:
  environment:
    name: Python 3.8
  variables:
    python: /opt/python/cp38-cp38/bin/python
  <<: *test

test:python3.9:
  environment:
    name: Python 3.9
  variables:
    python: /opt/python/cp39-cp39/bin/python
  <<: *test
