dist: bionic
language: python
cache: pip

stages:
  - name: Test (Linux)
  - name: Test (OSX)

.test-linux: &test-linux
  os: linux
  dist: bionic
  stage: Test (Linux)
  language: python
  cache: pip
  services: docker
  before_install: ci/travis/manylinux/before_install.sh
  install: ci/travis/manylinux/install.sh
  script: ci/travis/manylinux/script.sh
  after_success: ci/travis/manylinux/after_success.sh
  before_deploy: ci/travis/manylinux/before_deploy.sh

.test-osx: &test-osx
  os: osx
  stage: Test (OSX)
  language: generic
  cache:
    pip: cache
    directories:
      - $HOME/Library/Caches/Homebrew
      - $HOME/.pyenv_cache
  install: ci/travis/osx/install.sh
  script: ci/travis/osx/script.sh
  before_cache: ci/travis/osx/before_cache.sh
  after_success: ci/travis/osx/after_success.sh

jobs:
  include:
    - python: pypy3
      <<: *test-linux
    - python: 3.5
      <<: *test-linux
    - python: 3.6
      <<: *test-linux
    - python: 3.7
      <<: *test-linux
    - python: 3.8
      <<: *test-linux
    - env: PYTHON=python3.5
      name: "Python: 3.5"
      if: tag IS present
      <<: *test-osx
    - env: PYTHON=python3.6
      name: "Python: 3.6"
      if: tag IS present
      <<: *test-osx
    - env: PYTHON=python3.7
      name: "Python: 3.7"
      if: tag IS present
      <<: *test-osx
    - env: PYTHON=python3.8
      name: "Python: 3.8"
      <<: *test-osx


deploy:
  provider: script
  script: ci/travis/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: althonos/pyrodigal



# python:
# - 3.5
# - 3.6
# - 3.7
# - 3.8
# - pypy3
#
# before_install:
# - pip install -r ci/requirements.txt
#
# install:
# - python setup.py build_ext --inplace --debug
#
# script:
# - python -m coverage run -p -m unittest discover -v
#
# after_success:
# - python -m coverage combine
# - python -m coverage xml
# - codecov
#
# before_deploy:
# - python setup.py sdist bdist_wheel
# - twine check dist/*
#
# deploy:
#   provider: script
#   script: ci/travis/deploy.sh
#   skip_cleanup: true
#   on:
#     python: 3.8
#     tags: true
#     branch: master
#     repo: althonos/pyrodigal
#
# notifications:
#   email:
#   - althonosdev@gmail.com
